// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/monitor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PortMonitor_StreamPorts_FullMethodName = "/proto.PortMonitor/StreamPorts"
	PortMonitor_KillProcess_FullMethodName = "/proto.PortMonitor/KillProcess"
)

// PortMonitorClient is the client API for PortMonitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PortMonitorClient interface {
	StreamPorts(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PortList], error)
	KillProcess(ctx context.Context, in *PidRequest, opts ...grpc.CallOption) (*KillResponse, error)
}

type portMonitorClient struct {
	cc grpc.ClientConnInterface
}

func NewPortMonitorClient(cc grpc.ClientConnInterface) PortMonitorClient {
	return &portMonitorClient{cc}
}

func (c *portMonitorClient) StreamPorts(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PortList], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PortMonitor_ServiceDesc.Streams[0], PortMonitor_StreamPorts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, PortList]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PortMonitor_StreamPortsClient = grpc.ServerStreamingClient[PortList]

func (c *portMonitorClient) KillProcess(ctx context.Context, in *PidRequest, opts ...grpc.CallOption) (*KillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KillResponse)
	err := c.cc.Invoke(ctx, PortMonitor_KillProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortMonitorServer is the server API for PortMonitor service.
// All implementations must embed UnimplementedPortMonitorServer
// for forward compatibility.
type PortMonitorServer interface {
	StreamPorts(*emptypb.Empty, grpc.ServerStreamingServer[PortList]) error
	KillProcess(context.Context, *PidRequest) (*KillResponse, error)
	mustEmbedUnimplementedPortMonitorServer()
}

// UnimplementedPortMonitorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPortMonitorServer struct{}

func (UnimplementedPortMonitorServer) StreamPorts(*emptypb.Empty, grpc.ServerStreamingServer[PortList]) error {
	return status.Error(codes.Unimplemented, "method StreamPorts not implemented")
}
func (UnimplementedPortMonitorServer) KillProcess(context.Context, *PidRequest) (*KillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KillProcess not implemented")
}
func (UnimplementedPortMonitorServer) mustEmbedUnimplementedPortMonitorServer() {}
func (UnimplementedPortMonitorServer) testEmbeddedByValue()                     {}

// UnsafePortMonitorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortMonitorServer will
// result in compilation errors.
type UnsafePortMonitorServer interface {
	mustEmbedUnimplementedPortMonitorServer()
}

func RegisterPortMonitorServer(s grpc.ServiceRegistrar, srv PortMonitorServer) {
	// If the following call panics, it indicates UnimplementedPortMonitorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PortMonitor_ServiceDesc, srv)
}

func _PortMonitor_StreamPorts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PortMonitorServer).StreamPorts(m, &grpc.GenericServerStream[emptypb.Empty, PortList]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PortMonitor_StreamPortsServer = grpc.ServerStreamingServer[PortList]

func _PortMonitor_KillProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortMonitorServer).KillProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortMonitor_KillProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortMonitorServer).KillProcess(ctx, req.(*PidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PortMonitor_ServiceDesc is the grpc.ServiceDesc for PortMonitor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PortMonitor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PortMonitor",
	HandlerType: (*PortMonitorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KillProcess",
			Handler:    _PortMonitor_KillProcess_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPorts",
			Handler:       _PortMonitor_StreamPorts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/monitor.proto",
}
