// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/monitor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           string                 `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PidRequest) Reset() {
	*x = PidRequest{}
	mi := &file_proto_monitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PidRequest) ProtoMessage() {}

func (x *PidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PidRequest.ProtoReflect.Descriptor instead.
func (*PidRequest) Descriptor() ([]byte, []int) {
	return file_proto_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *PidRequest) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

type KillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillResponse) Reset() {
	*x = KillResponse{}
	mi := &file_proto_monitor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillResponse) ProtoMessage() {}

func (x *KillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillResponse.ProtoReflect.Descriptor instead.
func (*KillResponse) Descriptor() ([]byte, []int) {
	return file_proto_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *KillResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *KillResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PortList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ports         []*PortInfo            `protobuf:"bytes,1,rep,name=ports,proto3" json:"ports,omitempty"`
	TotalMem      float32                `protobuf:"fixed32,2,opt,name=total_mem,json=totalMem,proto3" json:"total_mem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortList) Reset() {
	*x = PortList{}
	mi := &file_proto_monitor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortList) ProtoMessage() {}

func (x *PortList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortList.ProtoReflect.Descriptor instead.
func (*PortList) Descriptor() ([]byte, []int) {
	return file_proto_monitor_proto_rawDescGZIP(), []int{2}
}

func (x *PortList) GetPorts() []*PortInfo {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *PortList) GetTotalMem() float32 {
	if x != nil {
		return x.TotalMem
	}
	return 0
}

type PortInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          string                 `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
	Pid           string                 `protobuf:"bytes,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Cpu           float32                `protobuf:"fixed32,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Mem           float32                `protobuf:"fixed32,5,opt,name=mem,proto3" json:"mem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortInfo) Reset() {
	*x = PortInfo{}
	mi := &file_proto_monitor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortInfo) ProtoMessage() {}

func (x *PortInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_monitor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortInfo.ProtoReflect.Descriptor instead.
func (*PortInfo) Descriptor() ([]byte, []int) {
	return file_proto_monitor_proto_rawDescGZIP(), []int{3}
}

func (x *PortInfo) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *PortInfo) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *PortInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PortInfo) GetCpu() float32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *PortInfo) GetMem() float32 {
	if x != nil {
		return x.Mem
	}
	return 0
}

var File_proto_monitor_proto protoreflect.FileDescriptor

const file_proto_monitor_proto_rawDesc = "" +
	"\n" +
	"\x13proto/monitor.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1e\n" +
	"\n" +
	"PidRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\tR\x03pid\"B\n" +
	"\fKillResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"N\n" +
	"\bPortList\x12%\n" +
	"\x05ports\x18\x01 \x03(\v2\x0f.proto.PortInfoR\x05ports\x12\x1b\n" +
	"\ttotal_mem\x18\x02 \x01(\x02R\btotalMem\"h\n" +
	"\bPortInfo\x12\x12\n" +
	"\x04port\x18\x01 \x01(\tR\x04port\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\tR\x03pid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x10\n" +
	"\x03cpu\x18\x04 \x01(\x02R\x03cpu\x12\x10\n" +
	"\x03mem\x18\x05 \x01(\x02R\x03mem2~\n" +
	"\vPortMonitor\x128\n" +
	"\vStreamPorts\x12\x16.google.protobuf.Empty\x1a\x0f.proto.PortList0\x01\x125\n" +
	"\vKillProcess\x12\x11.proto.PidRequest\x1a\x13.proto.KillResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_monitor_proto_rawDescOnce sync.Once
	file_proto_monitor_proto_rawDescData []byte
)

func file_proto_monitor_proto_rawDescGZIP() []byte {
	file_proto_monitor_proto_rawDescOnce.Do(func() {
		file_proto_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_monitor_proto_rawDesc), len(file_proto_monitor_proto_rawDesc)))
	})
	return file_proto_monitor_proto_rawDescData
}

var file_proto_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_monitor_proto_goTypes = []any{
	(*PidRequest)(nil),    // 0: proto.PidRequest
	(*KillResponse)(nil),  // 1: proto.KillResponse
	(*PortList)(nil),      // 2: proto.PortList
	(*PortInfo)(nil),      // 3: proto.PortInfo
	(*emptypb.Empty)(nil), // 4: google.protobuf.Empty
}
var file_proto_monitor_proto_depIdxs = []int32{
	3, // 0: proto.PortList.ports:type_name -> proto.PortInfo
	4, // 1: proto.PortMonitor.StreamPorts:input_type -> google.protobuf.Empty
	0, // 2: proto.PortMonitor.KillProcess:input_type -> proto.PidRequest
	2, // 3: proto.PortMonitor.StreamPorts:output_type -> proto.PortList
	1, // 4: proto.PortMonitor.KillProcess:output_type -> proto.KillResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_monitor_proto_init() }
func file_proto_monitor_proto_init() {
	if File_proto_monitor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_monitor_proto_rawDesc), len(file_proto_monitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_monitor_proto_goTypes,
		DependencyIndexes: file_proto_monitor_proto_depIdxs,
		MessageInfos:      file_proto_monitor_proto_msgTypes,
	}.Build()
	File_proto_monitor_proto = out.File
	file_proto_monitor_proto_goTypes = nil
	file_proto_monitor_proto_depIdxs = nil
}
